name: Military Business
favicon: null
layout_spectrum: 0.7782106339000165
typography_spectrum: 0.03514242731034756
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8061804247554392
  lightness: 0.21154363779351115
  saturation: 0.15443958877585828
  rhythmicContrast: 0.5069030651357025
purpose: []
