name: Military Business
favicon: null
layout_spectrum: 0.74548
typography_spectrum: 0.03514242731034756
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#4a5055'
    - '#817869'
    - '#beb8a6'
    - '#2c2c2c'
  brandStrength: 0.5
  lightness: 0.21154363779351115
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
